// <auto-generated />
using System;
using FormBuilder.Core.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FormBuilder.Core.Data.Migrations
{
    [DbContext(typeof(DbContextCore))]
    [Migration("20190409051647_Initial_Db")]
    partial class Initial_Db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FormBuilder.Core.Domain.Models.Fields.Builder.BaseFieldBuilder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("FormBuildId");

                    b.Property<bool?>("IsRequired");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("FormBuildId");

                    b.ToTable("BaseFieldBuilder");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseFieldBuilder");
                });

            modelBuilder.Entity("FormBuilder.Core.Domain.Models.Forms.FormBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiredIn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FormBuilder");
                });

            modelBuilder.Entity("FormBuilder.Core.Domain.Models.Fields.Builder.Numbers.IntFieldBuilder", b =>
                {
                    b.HasBaseType("FormBuilder.Core.Domain.Models.Fields.Builder.BaseFieldBuilder");

                    b.Property<int?>("MaxValue");

                    b.Property<int?>("MinValue");

                    b.ToTable("IntField");

                    b.HasDiscriminator().HasValue("IntFieldBuilder");
                });

            modelBuilder.Entity("FormBuilder.Core.Domain.Models.Fields.Builder.Texts.TextFieldBuilder", b =>
                {
                    b.HasBaseType("FormBuilder.Core.Domain.Models.Fields.Builder.BaseFieldBuilder");

                    b.Property<int?>("MaxLength");

                    b.Property<int?>("MinLength");

                    b.Property<string>("Placeholder");

                    b.ToTable("TextField");

                    b.HasDiscriminator().HasValue("TextFieldBuilder");
                });

            modelBuilder.Entity("FormBuilder.Core.Domain.Models.Fields.Builder.BaseFieldBuilder", b =>
                {
                    b.HasOne("FormBuilder.Core.Domain.Models.Forms.FormBuild")
                        .WithMany("Fields")
                        .HasForeignKey("FormBuildId");
                });
#pragma warning restore 612, 618
        }
    }
}
